# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Subo < Formula
  desc "Suborbital CLI for building and deploying WebAssembly-based projects"
  homepage "https://suborbital.dev"
  version "0.5.4"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/suborbital/subo/releases/download/v0.5.4/subo-v0.5.4-darwin-arm64.tar.gz"
      sha256 "815eefd6e2f6594af69f0881e49070c4ff368d2b843c7bc0503bc836a954ac85"

      def install
        bin.install "subo"

        bash_output = Utils.safe_popen_read(bin/"subo", "completion", "bash")
        (bash_completion/"subo").write bash_output

        zsh_output = Utils.safe_popen_read(bin/"subo", "completion", "zsh")
        (zsh_completion/"_subo").write zsh_output

        fish_output = Utils.safe_popen_read(bin/"subo", "completion", "fish")
        (fish_completion/"subo.fish").write fish_output
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/suborbital/subo/releases/download/v0.5.4/subo-v0.5.4-darwin-amd64.tar.gz"
      sha256 "743507151118af7a2a9aacd7f108c492b2594ebc17f15c228039ae2f8b53d8ac"

      def install
        bin.install "subo"

        bash_output = Utils.safe_popen_read(bin/"subo", "completion", "bash")
        (bash_completion/"subo").write bash_output

        zsh_output = Utils.safe_popen_read(bin/"subo", "completion", "zsh")
        (zsh_completion/"_subo").write zsh_output

        fish_output = Utils.safe_popen_read(bin/"subo", "completion", "fish")
        (fish_completion/"subo.fish").write fish_output
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/suborbital/subo/releases/download/v0.5.4/subo-v0.5.4-linux-arm64.tar.gz"
      sha256 "7eaa09bf3932ee4d6281dcd861d6058077edb5c5cebe6b9c6db16f0d6c36094e"

      def install
        bin.install "subo"

        bash_output = Utils.safe_popen_read(bin/"subo", "completion", "bash")
        (bash_completion/"subo").write bash_output

        zsh_output = Utils.safe_popen_read(bin/"subo", "completion", "zsh")
        (zsh_completion/"_subo").write zsh_output

        fish_output = Utils.safe_popen_read(bin/"subo", "completion", "fish")
        (fish_completion/"subo.fish").write fish_output
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/suborbital/subo/releases/download/v0.5.4/subo-v0.5.4-linux-amd64.tar.gz"
      sha256 "94db660e5adcfdab3c95740bd2eab9843c694212ebfd717de9a32daecb41ddee"

      def install
        bin.install "subo"

        bash_output = Utils.safe_popen_read(bin/"subo", "completion", "bash")
        (bash_completion/"subo").write bash_output

        zsh_output = Utils.safe_popen_read(bin/"subo", "completion", "zsh")
        (zsh_completion/"_subo").write zsh_output

        fish_output = Utils.safe_popen_read(bin/"subo", "completion", "fish")
        (fish_completion/"subo.fish").write fish_output
      end
    end
  end

  test do
    assert_match "Subo CLI v#{version}", shell_output("#{bin}/subo --version")
  end
end
